services:
  consumer:
    build:
      context: .
      target: consumer
    networks:
      - common-net
    depends_on:
      - kafka

  producer:
    build:
      context: .
      target: producer
    networks:
      - common-net
    depends_on:
      - kafka

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092"
      - "9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_TLS_CLIENT_AUTH=none
    networks: 
      - common-net
    volumes:
      - 'kafka_data:/bitnami/kafka'

networks:
  common-net:
    driver: bridge

volumes:
  kafka_data:
