flowchart TD
%% Nodes
    topic1("/topic1")@{shape: lean-l}
    consumer1("Consumer Group 1")
    topic2("/topic2")@{shape: lean-l}
    consumer2("Consumer Group 2")
    retryTopic("/retryTopic")@{shape: lean-l}
    retryConsumerGroup("Retry Consumer Group")
    retriesDatabase(Retries DB)@{shape: database}
    cron(Every X amount of seconds)@{shape: delay}
    retryProducer("Retry Producer")

%% Edge connections between nodes
    topic1 --> consumer1 -->|failed| retryTopic
    topic2 --> consumer2 -->|failed| retryTopic
    retryTopic --> retryConsumerGroup --> retriesDatabase
    cron -..-> retryProducer --> retriesDatabase
    retryProducer --> |attempts+1|topic1
    retryProducer --> |attempts+1|topic2
